- name: Check if node is already registered in a swarm
  shell: '[ "$(docker info --format {% raw %}{{.Swarm.LocalNodeState}}{% endraw %})" = "active" ]' # noqa 206
  register: is_active
  ignore_errors: true
  changed_when: false
  tags: swarm

- name: Add worker to swarm
  shell: "docker swarm join --token {{ hostvars['manager1']['worker_token']['stdout'] }} {{ hostvars['manager1']['ansible_default_ipv4']['address'] }}:2377"
  when: is_active.rc == 1
  tags: swarm
