- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  changed_when: false
  tags: swarm

- name: Initialize Docker Swarm
  shell: docker swarm init --advertise-addr={{ ansible_default_ipv4.address }}:2377
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Get worker's join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  changed_when: false
  tags: swarm
